version: '3'

services:
  storage-postgres:
    image: 'postgres:10'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pas123
    command: ["postgres", "-c", "log_statement=all"]
